package mybatis.sample.model;

@SuppressWarnings("javadoc")
public class Test2 {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST2.ID
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST2.TEXT
     *
     * @mbg.generated
     */
    private String text;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TEST2.OBJ
     *
     * @mbg.generated
     */
    private byte[] obj;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST2.ID
     *
     * @return the value of TEST2.ID
     *
     * @mbg.generated
     */
    public Long getId() {
        return this.id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST2.ID
     *
     * @param id the value for TEST2.ID
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST2.TEXT
     *
     * @return the value of TEST2.TEXT
     *
     * @mbg.generated
     */
    public String getText() {
        return this.text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST2.TEXT
     *
     * @param text the value for TEST2.TEXT
     *
     * @mbg.generated
     */
    public void setText(String text) {
        this.text = text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TEST2.OBJ
     *
     * @return the value of TEST2.OBJ
     *
     * @mbg.generated
     */
    public byte[] getObj() {
        return this.obj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TEST2.OBJ
     *
     * @param obj the value for TEST2.OBJ
     *
     * @mbg.generated
     */
    public void setObj(byte[] obj) {
        this.obj = obj;
    }
}